spring:
  application:
    name: Spring_or_death_app
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /app

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: spring.app
  mapper-locations: classpath*:mappers/**/*-mapper.xml

logging:
  level:
    root: info
    com.sh: debug